### ISSUE TITLE
Add the first Milestone of the project

### ISSUE THREAD

**Issue by RubenTheCoder** [RubenTheCoder/SR.com#4]
Add a Milestone for setting up the GitHub repository

### Milestone tasks
> Things to create tasks for in the Milestone
- [x] Add Readme's, descriptions and tags
- [x] Add issue and pull request templates
- [x] Set up the project wiki
- [x] Set up actions and workflows
- [x] Configure security
- [x] Complete all community standards tasks
